name: lamasatboutiquemyapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  icons_plus: ^5.0.0
  cupertino_icons: ^1.0.6
  hexcolor: ^3.0.1
  intl: ^0.18.1
  another_carousel_pro: ^1.0.2
  google_sign_in_web: ^0.12.3

  firebase_core: ^2.15.0
  firebase_auth: ^4.11.0
  cloud_firestore: ^4.8.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.7
  flutter_bloc: ^8.1.6

  cloudinary_dart: ^0.0.11
  http: ^1.1.0
  flutter_dotenv: ^5.1.0

  google_sign_in: ^6.1.5
  firebase_database: ^10.2.5
  the_apple_sign_in: ^1.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/card.png
    - images/fashion.jpg
    - images/d1.png
    - images/d2.jpg
    - assets/.env
